### ISSUE TITLE
Create other JSON examples

### ISSUE THREAD

**Issue by glatard** [INCF/apine#1]
From datasets with:
- [ ] Code
- [x]  Sidecar JSON files for nifti images (anatomical and/or functional)
- [ ]  Imaging modalities other than T1w and inplaneT2 (PD, etc)
- [x]  Task stimuli files
- [ ]  Physiological recordings
- [ ]  Behavioral experiments
- [x]  Diffusion imaging data
- [ ]  Fieldmap data
- [ ]  Scans files
- [ ]  Participants phenotypes
- [x]  Participants JSON files
- [x]  Multiple sessions
- [ ]  Session files
- [ ]  Multiple sites

**Comment by crocodoyle** [comment]
I'll do ds114!

**Comment by crocodoyle** [comment]
Apparently @gkiar is doing ds114

**Comment by jbpoline** [comment]
I'm doing ds031 : the my connectome project - but it feels really inefficient to do it by hand - I think I'll switch to using pybids

**Comment by gkiar** [comment]
@jbpoline I'm making progress on a parser - should have a working prototype (tested on ds114 as @crocodoyle said) by end of day. I'll comment back here when it's pushed.

**Comment by gkiar** [comment]
The parser generated in https://github.com/INCF/apine/commit/772daf5a1c5761021b90d40a9e6e77b593975721 was used on ds114 and checks off 5 of these boxes. Looking for more datasets to test on now

**Comment by gkiar** [comment]
Made many improvements. Just pushed examples for all examples in the INCF/BIDS-example repo [here](https://github.com/INCF/apine/tree/master/examples). We should proof read them manually to find any holes in the conversion.
